✨ Add Keplr Sign-In button on top of Authcore Sign-In button
likecoin/like-co pull request #1568
Opened 2021-12-16 09:35 UTC by shellyYG

2021-12-21 16:56 UTC, williamchong requested changes

2021-12-21 16:56 UTC, williamchong commented on util/cosmos/iscn/sign.js
> +        '@id': userId,
```suggestion
        '@id': `${EXTERNAL_URL}/${userId}`,
```

2021-12-21 16:56 UTC, williamchong commented on pages/in/widget/iscn/index.vue
> +      'loginByCosmosWallet',
Remove if not used

2021-12-21 16:56 UTC, williamchong commented on store/modules/actions/payment.js
> +    if (metadata && !isNonLikerKeplrConnected) await api.apiPostTxMetadata(txHash, metadata);
Note: Maybe we should allow submitting metadata via a signature from the sender address later

2021-12-21 16:56 UTC, williamchong commented on util/cosmos/iscn/constant.js
> +  },
Are these new fields used in this PR?

2021-12-21 16:56 UTC, williamchong commented on util/cosmos/iscn/sign.js
> -import { EXTERNAL_URL } from '../../../constant';
Please keep `EXTERNAL_URL`

2021-12-22 09:34 UTC, shellyYG commented on util/cosmos/iscn/constant.js
> +  },
No, forgot to remove :P

2021-12-22 15:11 UTC, williamchong approved these changes

2021-12-22 15:11 UTC, merged